default_nicknames:
  n0kbnmk: 'Igor'
  Bartek J.: 'Toxic Blowjob'
  LELOŚ: 'dipl0d0k'
  ɥsnqɯᴉq: 'home of sexuals'
  NieobliczalnyPL1: 'ObliczalnyPL1'
extensions:
  - 'member_count'
channels:
  text:
    colors : 801502702717894726
    main : 801503407406841949
  voice:
    count: 801732844857589770
ready_message: 'Ready ✅ <@488954369769734146>'
token: 'ODAxNzQxNjU0MjY3OTIwMzk1.YAlGGg.ytn7t5IBdEjI9cg5iKayHPH8NUI'